apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj10-poi-map-app-dev
  annotations:
    argocd/app-name: ryanj10-poi-map-app-dev
    backstage.io/kubernetes-id: ryanj10-poi-map-app
    backstage.io/kubernetes-namespace: ryanj10
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/ryanj10-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/ryanj10/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/ryanj10/deployments/ryanj10-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/ryanj10-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://ryanj10-poi-map-app-ryanj10.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-ryanj10
  consumesApis:
    - gateway-api-ryanj10
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj10
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
